### ISSUE TITLE
Anführungszeichen Fehlermeldung Termin hinzufügen

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_prozer#102]
Kalender, Termin hinzufügen:
Die Fehlermeldung hat falsch maskierte Anführungszeichen:

Sie können in diesem Projekt keinen Termin eintragen
Das &quot;von&quot; Datum muss vor dem &quot;bis&quot; Datum sein

**Comment by frag-seb** [comment]
Ich die Anführungszeichen sind Absicht..
