### ISSUE TITLE
Admin Rechte Projekt entziehen - alle Rechte weg

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#109]
Als Prozer Admin habe ich einer Person A die Admin-Rechte auf dem Projekte in der Übersicht entzogen. Dann blätterte ich auf Seite 2, fügte einer anderen Person B die Admin Rechte hinzu, blätterte auf Seite 1 zurück, Person A hatte jetzt auch alle anderen Rechte nicht mehr. 
Das ist mir bei zwei Projekten aufgefallen, bei einem war es nicht passiert. Komisch

**Comment by frag-seb** [comment]
Also das problem ist, das ein Admin immer alle rechte hat. Das bekommt man auch so angezeigt. 
Wenn die Person A jetzt keine rechte hat, ausser Admin dann ist das verhalten Ansich richtig.

ABER die Anzeige wurde nicht aktualisiert, das problem habe ich schon mit einem Commit behoben, ändert man den status Admin werden die checkbox neue geladen.

Issues #134
