### ISSUE TITLE
Schönheitsfehler - Anzeige Buchstabe in der Projektauswahl

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#11]
Kompliment: Sehr cool, dass ich ein Projekt mit dem Anfangsbuchstaben auswählen kann ( Bsp.: Zeitbuchung) Muss auch in die Anleitung, da nur zufällig von der Kollegin erfahren. 

Schönheitsfehler: Bsp.: Projektname "Test Ende"  - > Tippe das "E" -> Gehighlightet wird das "e" von Test und nicht der Eigentliche Anfangsbuchstabe "E" von Ende, der wirksam ist 
Hat meine Kollegin ca 20 Min. verzweifeln lasse und weitere 10 Min. bis ich es kapiert und ihr erklärt hatte :-)

**Comment by frag-seb** [comment]
Ist der Fehler noch aktuell und wenn wo ist dieser Fehler zu finden.

**Comment by Christian-H** [comment]
Also bei meinem Test mit dem Projektnamen "Test Ende" und dann der Projektauswahl im Kalender, taucht der Fehler noch auf. Ist aber ein Schönheitsfehler und hat niedrigste Priorität.

**Comment by staabm** [comment]
Für mich sieht es so aus, als wäre der "Fehler" nur im CSS, da bei dem aktiv ge'highlighteten eintrag die Markierung des "getroffenen" Buchstaben gar nicht ersichtlich ist.

**Comment by frag-seb** [comment]
Danke Thomas ... 

Ich hab da kein highlighting gesehen :D
