### ISSUE TITLE
Fehler Projektrechte zuteilung als Admin

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#134]
Als normaler Admin eines Projektes kann man andere per Häkchen zu Admins machen oder ihnen das Adminrecht wegnehmen. Die andere Rechte können aber nicht verändert werden. Work around ist, eine Person aus dem Projekt zu löschen und wieder neu mit den entsprechenden Rechten anzulegen. 
Als Superadmin klappt es per Häkchen Personen die Rechte einzuräumen oder wegzunehmen.

**Comment by frag-seb** [comment]
Servus Jan und Christian, ich hab es auf einem Test System gefixt, Pull Request ist auch schon gemacht. 

@jan Ich muss mal schauen wie ich einzelne pull requests machen kann über die Console oder geht es so mit den requests?
