### ISSUE TITLE
Verbesserungen der Log-Datei Auswertung

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#139]
Komisch ist, dass egal, was ich für ein Filter setze, es immer maximal 1000 Ergebnisse sind. Mmh, das heißt doch, dass evtl. Ergebnisse fehlen.

Sehr gut wäre es,
- wenn man die Log-Dateien für ein Projekt durchsuchen könnte. 
- wenn es ein Freifeld für das angeben eines Filters gebe.
- wenn man nach Dateinamen suchen könnte.

**Comment by frag-seb** [comment]
Also wenn kein Filter gesetzt ist würde ich bei 1000 oder 2000 bleiben, wenn ein filter gesetzt ist könnte man eventuell verzichten oder man könnte eine checkbox "alle anzeigen" in das Form aufnehmen.

Aktuell kann es wirklich sein das du Datensätze nicht angezeigt bekommst.

**Comment by Christian-H** [comment]
Ja, dann doch bitte eines von beiden umsetzen:
- keine Begrenzung bevorzugt oder halt 
- Checkbox "Alle Ergebnisse anzeigen"

**Comment by frag-seb** [comment]
Hab jetzt eine Begrenzung auf 2000 und dann "alle Anzeigen" kann es noch um benennen auf "Alle Ergebnisse anzeigen" ändern.

**Comment by Christian-H** [comment]
... sehr gut, dann ändere das vom Namen her noch. Vielleicht ist "Resultate" kürzer als Ergebnisse :-) vom Platz her ...

**Comment by frag-seb** [comment]
Also selbst bei mir reicht das noch nicht aus, aber die letzten Ergebnisse sind meist schon uninteressant.... Oder man hat nicht genau gefiltert.


    - Log Project Filter
    - Textfeld für Dateiname Suche, wenn nach einem Object gesucht wird.…
       Der Name der Datei wird auch jetzt angezeigt.
    - Checkbox alle Anzeigen

**Comment by Christian-H** [comment]
Hört sich doch gut an, wenn das jetzt geht. Dann reicht das doch auch?

**Comment by frag-seb** [comment]
Ja,  @dergel muss wenn es fertig ist nur noch zusammen führen.
