### ISSUE TITLE
Idee - alternative, verknappte E-Mail Ansicht

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#144]
Anbei ein screenshot, wie yahoo oder web.de die e-mails darstellen als anregung /diskussionsgrundlage, wie eine 2. alternative, verkürzte e-mail ansicht aussehen könnte.

![screenshot-e-mail-darstellungen](https://cloud.githubusercontent.com/assets/2972659/2633122/ed7134ea-be6a-11e3-85c4-f90c6e8f9993.jpg)

**Comment by dergel** [comment]
ich schliesse das hier, damit wir an der richtigen Stelle weitermachen .. den screenshot übernehme ich dorthin
