### ISSUE TITLE
Nach dem erfolgreichem Versand einer E-Mail direkt in die Inbox zurück

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#145]
Wenn ich eine E-Mai erfolgreich versendet habe, dann brauche ich dies nicht zu lesen, sondern würde mich freuen direkt in der Inbox wieder zu landen und diesen Extra-Klick zu vermeiden. Nur Fehlermeldungen würde ich gerne lesen :-)

**Comment by frag-seb** [comment]
Gibt es in der Prozer architektur einen redirect oder sollen wir das über eine Javascript function machen?

**Comment by frag-seb** [comment]
Es kommt eine neue js function die ein verzögerte callback macht. 

Ich hab die schon in einem andern Issues fertig...
