### ISSUE TITLE
Email in neuem Tab öffnen

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_prozer#146]
Aktuell werden Emails in der übersicht "aufgeklappt" über ein `javascript:` im a[href]. Deshalb ist es nicht möglich eine bestimmte email in einem neuen Tab zu öffnen.

Wenn das dortige javascript in das `onclick` wandern würde könnte man erreichen dass durch strg+click oder 3. maustaste (open in new tab) die email in einem neuen fenster dargestellt würde.

Aktuell:
```
<a href="javascript:pz_open_email('XXZZ','/screen/emails/email/?search_orderby=createdesc&amp;mode=view&amp;email_id=XXZZ')">
  <span class="title">Mein Email Titel</span>
</a>
```

Neu:
```
<a href="/screen/emails/email/?search_orderby=createdesc&amp;mode=view&amp;email_id=XXZZ" onclick="pz_open_email('XXZZ',this.href)">
  <span class="title">Mein Email Titel</span>
</a>
```

dazu müsste dann noch für diese urls wie
`/screen/emails/email/?search_orderby=createdesc&mode=view&email_id=XXYYYZZ`
eine reguläre html view geben und die das aktuell gerenderte markup nur im AJAX fall gerendert.

(Im prinzip so wie man es mit PJAX machen würde).

**Comment by dergel** [comment]
ist bereits drin .. klick auf icon - neues fenster/tab
