### ISSUE TITLE
Seiten nachladen problem ..

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#152]
zum Beispiel, mal lädt in der Inbox die Seite 2 nach, manchmal nicht und man muss erst auf die 2 klicken im Firefox. Wieso und weshalb es mal funktioniert und mal nicht, wissen wir nicht :-)

**Comment by Christian-H** [comment]
Testen, ob es noch so ist

**Comment by frag-seb** [comment]
double
#297
