### ISSUE TITLE
Anderes Postfach - Anhang weiterleiten

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#153]
Wenn man in einem anderen Postfach ist (Bsp.  ich im Agentur-Postfach), dann kann man zwar die Mail weiterleiten, aber Anhänge werden nicht mitgeschickt. Ich nehme an, dass es mit der Korrektur von Issue 148 zusammen hängt.

**Comment by dergel** [comment]
habe den einen issue rausgezogen .. ist wohl was anderes
