### ISSUE TITLE
E-Mail Inbox - Laufzeitfehler

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#161]
heisst, die Mail taucht mehrfach auf, ist aber eigentlich nur einmal da

**Comment by dergel** [comment]
kannst du das einkreisen ? .. kann es sein, dass gerade eine email geloescht wurde und man dann weiterblaettert ?

**Comment by Christian-H** [comment]
nö, ist mir auch schon länger nicht passiert. Du sagtest es damals bei der Fehlerbeschreibung, es wäre ein Laufzeitfehler und so soll ich es in github eintragen :-)

**Comment by dergel** [comment]
ist mir nicht mehr passiert. Früher schon. Ich glaube da gab es ein Problem mit der Zeit, so dass das System dachte, die Mail wäre noch nicht ausgeliefert worden.. aber passt nun
