### ISSUE TITLE
Ajax Timeouts

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_prozer#167]
wenn man sich im Posteingang befindet laufen Intervall gesteuert AJAX requests.
bei einer langsamen Verbindung oder hoher last auf dem Server kann es dazu kommen dass bereits ein weiteres AJAX Request gefeuert wird, obwohl das vorherige schon läuft.

Bestenfalls würden die AJAX Request auf einen Timeout laufen, kurz bevor das nächste beginnt (z.b. Intervalldauer 10 sekunden, Timeout 9 sekunden).

konkret in meinem Fall sind folgende Urls betroffen
http://prozer.modulvier.com/screen/emails/inbox/?mode=getnew&search_orderby=createdesc&date=2014-08-19+17%3A54%3A27
http://prozer.modulvier.com/screen/tools/tracker/

ggf. würde es sich auch anbieten den Intervall zu verlängern (Backoff) wenn ein AJAX request mal nicht erfolgreich gelaufen ist.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_prozer/issues/167
