### ISSUE TITLE
Email in neuem Tab öffnen

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_prozer#168]
wenn man den link zu einer Email mittels 3. Maustaste (oder STRG+Click) benutzt sollte sich im neuen Tab die komplette Seite laden und die Email aufgeklappt sein.

Aktuell öffnet sich nur ein leerer neuer Tab und in der Adresszeile steht ein stück Javascript

**Comment by staabm** [comment]
Heute wieder drüber gestolpert, dass mittels mittlere Maustaste nen "kaputter Tab" sich öffnet, der nix anzeigt

**Comment by dergel** [comment]
war schon in einem anderen Issue.. Klick auf das Icon öffnet die Text oder HTML Mail im neuen Fenster/oder halt Tab. Klick auf den Text öffnet es als text oder iframe.
