### ISSUE TITLE
Kalender :: Termin "Anhänge" falscher Text

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_prozer#175]
Wenn ich einen Eintrag auswähle und dann über den Editierbutton gehe, ein Mousedown auslöse und die Maus vom Button ziehe (will editieren, breche es aber ab), erscheint auf der linken Seite bei "Termin hinzufügen" unter Anhänge `[translate:files_for_upload]`

**Comment by frag-seb** [comment]
Servus, kannst Du mir das etwas genauer erklären ich versteh nicht was damit gemeint ist.

**Comment by tbaddade** [comment]
Browser: Safari

Du gehst in den Kalender > Tagesansicht.

Links ist das Formular "Termin hinzufügen" offen.
Rechts suchst du dir einen Eintrag im Kalender aus. Klickst auf diesen und es erscheint ein Popover. Dort machst du nur ein Mousedown (Maustaste gedrückt lassen) auf den Editier/Löschen/Schließen Button und ziehst den Cursor ein wenig.
In der linken Spalte das rote Feld für den Upload beobachten.

**Comment by frag-seb** [comment]
Der Fehler gefällt mir :D ist nur auf dem Mac so :D 
Ist ein Fehler in der fileuplader.js ....

**Comment by frag-seb** [comment]
Also hab es mir genau angesehen, das script hat schon sehr viele schwächen... 
Wenn ich an diesem Bug wirklich "an diesem Script" was es so ändern soll, das es Browser kompatibel wird, brauch dafür doch sehr lange.... 

Möglichkeiten
1) so lassen, mit dem wissen das es nicht besser wird.
2) wir überarbeiten das Script, braucht viel Zeit
3) wir versuchen ein Update einer neueren version, mit den bedenken das wir neue Bugs schaffen...

Diskussion erwünscht!!!!!!

**Comment by frag-seb** [comment]
Das würde den Bug beheben...
https://github.com/frag-seb/redaxo_prozer/tree/Issues_175

**Comment by frag-seb** [comment]
Ich werde Montag noch das ganze auf Windows testen und dann PR aufmachen.

**Comment by frag-seb** [comment]
ec51a4b4d4b2834b34be226e15a6cd3d3bcb2074

Ist schon gefixt..
