### ISSUE TITLE
Kalender :: Slashes werden angezeigt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_prozer#177]
Bei den Terminen müsste vor der Ausgabe ein stripslashes() kommen.

**Comment by frag-seb** [comment]
Ist der Fehler noch aktuell?

**Comment by tbaddade** [comment]
> Ist der Fehler noch aktuell?

Ja. Gib einfach mal `Test "Termin"` ein

**Comment by frag-seb** [comment]
Check, hab's gefunden..

**Comment by frag-seb** [comment]
Den Fehler im Calendar kann ich problem los fixen, kommt auch morgen (sitze in der bahn, kaum Empfang) ein Commit.

Die Anzeige im Form ist aber ein xForm fehler, was ich nur mit rücksprache fixen werde.

**Comment by tbaddade** [comment]
Ich hatte grad bei einer Adresse auch Backslashes gesehen. Kann du das mal prüfen.

Das sah im Feld Vorname so aus:
`Vorname\, Borname\, Corname`

Editiere ich den Datensatz ist alles gut. Daher vermute ich das dies durch syncen passiert sein könnte.

**Comment by frag-seb** [comment]
Wie wurde die Adresse erzeugt?

Ich hab es jetzt mal über's Web getestet und der fehler tritt bei mir nicht auf.

**Comment by tbaddade** [comment]
> Wie wurde die Adresse erzeugt?

Das weiß ich eben nicht. Hatte diese nur im Adresspool gesehen. Eventuell über Carddav.

**Comment by frag-seb** [comment]
ok, dann würde ich gerne ein neues Issues aufmachen. Das wäre ja dann ein andere Fehler..
