### ISSUE TITLE
Kalender :: ausgewählten Tag die class "selected" zuweisen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_prozer#179]
Oben links der Kalender. Der aktuell ausgewählte Tag bzw. Tage in der Wochenansicht bekommt die class "selected"

Müsste dann so aussehen.
`<td class="weekday event selected"> ... </td>`

CSS ist bereits definiert.

**Comment by frag-seb** [comment]
Kannst du mir die anderen Tickets von dir heute auch assignen.. 

Werde sie am we erledigen. 😃

**Comment by frag-seb** [comment]
@tbaddade Wie soll das verhalten in der Wochenansicht sein, sollen dann mehrere Tage die Class bekommen?

**Comment by tbaddade** [comment]
> Wie soll das verhalten in der Wochenansicht sein, sollen dann mehrere Tage die Class bekommen?

Ja
