### ISSUE TITLE
Darstellung in IE 10.0 unter Windows 8 fehlerhaft

### ISSUE THREAD

**Issue by UliK** [yakamara/redaxo_prozer#18]
Beispiele:
* ein neuer Termin im Kalender wird zwar mit der richtigen Uhrzeit, aber optisch an der falschen Stelle (ca. 5 Stunden vorher) angezeigt.
* Bei Klick auf "Teilnehmer" im Projekt erscheint eine Fehlermeldung (Seite kann nicht geöffnet werden)

Mit Firefox funktioniert unter Windows8 alles prima.

**Comment by frag-seb** [comment]
Ich kann diesen Fehler nicht nachspielen, ist er noch aktuell?

**Comment by dergel** [comment]
ich denke nicht .. irgendwann hatte ich das mal in einem anderen Issue behoben..
