### ISSUE TITLE
Zeiterfassung für Benutzer

### ISSUE THREAD

**Issue by Perzmann** [yakamara/redaxo_prozer#184]
Es wäre vielleicht ganz schön wenn man eine Zeiterfassung einbauen könnte. Für Projekte und auch als Stechuhr für Mitarbeiter/Benutzer im Team.

**Comment by dergel** [comment]
habe das bei einem anderen Issue geschrieben. Sorry erst jetzt. Leider sehe ich das bei Prozer nicht. Einerseits finde ich diese Art der Erfassung nicht so sinnvoll, und auch im Browser ist sowas ziemlich sicher nicht sehr zuverlässig zu lösen. Danke aber für die Idee
