### ISSUE TITLE
Kalender :: 2-Wochen Ansicht Termin anlegen

### ISSUE THREAD

**Issue by chip75** [yakamara/redaxo_prozer#188]
Fehlerhafte Darstellung der Wochenansicht (ggf. auf 1 Wocheansicht springen?)

![bildschirmfoto 2014-12-08 um 10 58 12](https://cloud.githubusercontent.com/assets/1301303/5337494/925436d2-7ec9-11e4-9b8b-2fcbf77bcf75.png)

**Comment by tbaddade** [comment]
@dergel Die Breite müsste via inline-style angepasst werden. Von 72px auf 45px.

**Comment by frag-seb** [comment]
ich bin mir nicht sicher ob die breite nicht irgendwo noch hard gecodet steht, bitte dann nochmal prüfen ob das verschieben der Termine ohne Probleme funktioniert.

**Comment by frag-seb** [comment]
Sollte auch noch merged werden #276

**Comment by dergel** [comment]
die 2 wochenansicht wird entfernt.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_prozer/issues/230
