### ISSUE TITLE
Anmerkungen Wiki - Überschriften, Fehler Links

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#191]
Ich finde die Darstellung der Überschriften zu groß mit H1 - 31,5 px, H2 -  24,5 px, H3 - 21px
Entweder bitte noch eine h4,h5 oder evtl h6 einfügen oder die h1 mit 21 px anzufangen wäre mein Vorschlag.

Bei den Links habe ich Probleme, dass es mir am Ende der Links ein a> anfügt und die nachfolgenden Inhalte auch damit verlinkt sind. In der Hilfe finde ich keine Lösung dafür. 
![wiki-fehler-links-20141210](https://cloud.githubusercontent.com/assets/2972659/5373820/58fa0e88-805a-11e4-898a-8ff0c7df5b4f.jpg)

**Comment by tbaddade** [comment]
@gharlan Der Fehler passiert bei Eingabe von Urls

Bsp. Eingabe
````
* Beitrag: http://www.sistrix.de/news/sistrix-content-discovery/#responds
```

Ausgabe
```
<li>Beitrag: <a href="http://www.sistrix.de/news/sistrix-content-discovery/#responds"><a href="http://www.sistrix.de/news/sistrix-content-discovery/#responds</">http://www.sistrix.de/news/sistrix-content-discovery/#responds</</a>a></li>
```

Kannst du mal schauen

**Comment by gharlan** [comment]
Ist ein Fehler in dem Markdown-Parser den wir verwenden.
Leider wird der nicht mehr weiterentwickelt (jedenfalls reagiert der Entwickler nicht mehr auf Issues).

Daher müssen wir schauen, ob wir es selbst in dem Parser fixen, oder eventuell den Parser wechseln. Das ist wiederum auch nicht so ganz einfach da überhaupt erst mal einen guten zu finden, der das gleiche bietet (Task-Lists etc.).

**Comment by frag-seb** [comment]
@gharlan Der Code führ es zwei mal aus, einmal dadurch das http:// davor steht, das wird zum Link umgewandelt (funktioniert) und dann wird der Link <a href="">...</a> noch mal geparst und erkannt. 
Da geht dann was schief

**Comment by gharlan** [comment]
Das Problem tritt aber nur bei verschachtelten Listen auf, wenn ich das richtig sehe.

**Comment by frag-seb** [comment]
genau, es wird beim ersten listen Punkt zum link und dann wird versucht aus dem Link ein link zumachen ... So in etwa

**Comment by frag-seb** [comment]
das geht
<a href="www.google.de">www.google.de</a>

das nicht
<a href="http://www.google.de">http://www.google.de</a>

**Comment by frag-seb** [comment]
#redaxo_prozer/vendor/kzykhys/ciconia/src/Ciconia/Renderer/HtmlRenderer.php

```php
/**
     * @param string|Text $content
     * @param array       $options
     *
     * @return string
     */
    public function renderLink($content, array $options = array())
    {

        $options = $this->createResolver()
            ->setRequired(array('href'))
            ->setDefaults(array('href' => '#', 'title' => ''))
            ->setAllowedTypes(array('href' => 'string', 'title' => 'string'))
            ->resolve($options);

        $tag = new Tag('a');
        $tag->setText($content->getUrlText());  // getUrlText() is a new method 
        $tag->setAttribute('href', $options['href']);

        if ($options['title']) {
            $tag->setAttribute('title', $options['title']);
        }

        return $tag->render();
    }
```

#redaxo_prozer/vendor/kzykhys/ciconia/src/Ciconia/Common/Text.php

```php
    /**
     * Returns internal string value
     *
     * @return string
     */
    public function getString()
    {
        return $this->text;
    }

    /**
     * Returns internal string value
     *
     * @return string
     */
    public function getUrlText($param = 'host')
    {
        $url = parse_url($this->text);
        return $url[$param];
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getString();
    }
```

**Comment by gharlan** [comment]
@frag-seb Danke für's Schauen! Hab es allerdings anders gelöst: https://github.com/gharlan/Ciconia/commit/4c30b0c5b928f8b7e21600b2f07dbb392a9033f6
