### ISSUE TITLE
Fehler - Projektrecht "Kalender [Jobs]"

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#20]
Wenn bei einem Projekt nur das Recht "Kalender [Jobs]" aktiviert, tritt der Fehler auf, dass im Kalender (Web) kein Job gebucht werden kann (rote Fehlermeldung, dass man keine Jobs buchen kann). 
Sobald das Recht "Kalender [Termine]" zusätzlich aktiviert wird, können auch Jobs gebucht werden.

**Comment by frag-seb** [comment]
Bei mir verhält sich dieser Fehler etwas anders, ob ich Jobs oder Termine dem User gebe, kann beides durch geführt werden.

Ist das jetzt nur bei mir so oder hat sich das auch bei dir geändert?

**Comment by Christian-H** [comment]
Hat sich bei mir auch geändert. 
Wenn ich nur Jobs als Recht angebe, dann kann ich Jobs und Termine eintragen. 
Wenn ich nur Termine als Echt angebe, dann kann ich KEINEN Job oder Termin eintragen. 

Bitte korrigieren. Danke

**Comment by frag-seb** [comment]
War doch eine harte Nuss :D

**Comment by Christian-H** [comment]
Okay, kann ich aber nachvollziehen. Danke
