### ISSUE TITLE
Archivierte Projekte - User können nur eigene E-Mails öffnen

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#201]
Wat fürn sch... User und auch ProjekteAdmins können nicht alle E-Mails in einem archivierten Projekt lesen, sondern nur die eigenen. 
Ich, als Obermufti kann alle E-Mails öffnen.

**Comment by frag-seb** [comment]
Servus Christian, ich bin mir nicht sicher ob das ein Bug ist, es wird nur User erlaubt die E-Mails zu lesen, wenn das Projekt nicht Aktiv ist.

**Comment by Christian-H** [comment]
Ich bin mir aber sicher, dass es ein BUG ist :) Wenn die Leute denken, dass sie dann nicht mehr an die Infos kommen, dann brauche ich gar kein Projekt mehr zu archivieren. DieFunktion wäre sinnlos. Zudem war in dem alten Prozer es genauso und hatte sich so bewährt.

**Comment by frag-seb** [comment]
Sorry für die Frage, ich kann nur sehen, wie es im Code steht. Wenn ich es nicht besser weiß, muss ich nachfragen.
