### ISSUE TITLE
Default Einstellung - E-Mail Konto ändern können

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#22]
Im Moment wird per default das E-Mail Konto genommen, welches als erstes angelegt wurde. Wenn es aber mehrere werden, möchte man evtl. auch ein anderes E-Mail Konto als default Konto haben und dies nicht nur darüber lösen möchten, alle Kontos wieder zu löschen und sie dann neu anzulegen.

**Comment by frag-seb** [comment]
Wie oft kommt es vor das mehr als 10 E-Mail adressen vorhanden sind?

**Comment by Christian-H** [comment]
... bei uns noch nie. wir haben nur 2-3 E-Mail Adressen. Da es ja aber für alle ist, bestimmt gibt es geeks, die mehr als 10 E-Mail Adressen haben, aber ich würde nicht sagen, dass wir die bedienen müssen. Wieso? Was ist der Hintergrund zu der Frage? ....

**Comment by frag-seb** [comment]
Ich hab das jetzt mir drag and drop gemacht (sehr sehr cool :D ), wenn mehr als 10 E-Mail Adressen angelegt sind kommt eine neue Seite. Das würde dann nicht so gut gehen, ich würde das gerne auf 20 hochschrauben und dann gut sein lassen.

Ist das ok?

**Comment by Christian-H** [comment]
okay

**Comment by frag-seb** [comment]
Ich hab die Lösung völlig falsch verstanden.
 
Wäre es ok wenn ich einen Button noch einfüge damit man auch dort seine Default E-Mail ändern kann?
