### ISSUE TITLE
Projektinfo - Erstelldatum hinzufügen und anzeigen

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#221]
dann kann man manchmal einfacher entscheiden, bo es archiviert werden soll

**Comment by frag-seb** [comment]
Kannst du mir bitte genauer erklären wo diese Information hin stehen soll.

**Comment by Christian-H** [comment]
Gute Frage. Also in der Projetk übersicht steht noch schon das Erstelldatum und der Projektverwalter. An dem Ort, wo ich aber entscheide, ob ich ein Projekt archiviere oder nicht, in "Aktuelles" steht es nicht. Ich habe jetzt darüber noch einmal nachgedacht, welche Informationen für diese Entscheidung sinnvoll sein können:
- Erstelldatum
- erstellt von wem 
- Datum letzte Aktion (Termin, Job, Datei, E-Mail archiviert, ...)
- Person, die die letzte Aktion durchgeführt hat. 

Wenn es möglich ist diese Infomartion darunter sinnvoll und grafisch angemessen anzulegen, ohne großen Zeitaufwand 1-2 Std. würde ich das befürworten einzufügen.  
Persönlich würde mir das in dem Kasten unter dem "abschicken" Button reichen. Muss man mal sehen, wie das aussieht?

**Comment by frag-seb** [comment]
Hi Christian,

sollte machbar sein, werde mich später damit beschäftigen.
Mir ist aber, als ich mir das angesehen habe, noch was aufgefallen was ich nicht versteh.

1) Ich versende eine E-Mail für ein Projekt 
    -> Warum wird das nicht ins log/Historie geschrieben?
    -> Woran erkenne ich ob es eine ausgehende oder eingehende E-Mail ist?

**Comment by Christian-H** [comment]
Gute Frage, aber keine Ahnung, wieso es nicht in die Log/Historie geschrieben wird. Wenn es beides nicht aufwendig ist und nichts dagegen spricht, bitte als Issues anlegen und erledigen.

**Comment by frag-seb** [comment]
Wäre super wenn du mir bei den Bezeichnungen behilflich bist..
![meta_info](https://cloud.githubusercontent.com/assets/1322118/7185549/ad30d0b4-e463-11e4-9da8-982c7881682a.png)

**Comment by Christian-H** [comment]
Bitte benutze:
last user action
und 
last update
