### ISSUE TITLE
Kalender - Wochenansicht 

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#230]
Die 2 Wochenansicht ist im momentanen Stand nicht gut nutzbar wegen der Darstellung. Sinnvoller wäre dann wohl eine Wochenansicht. (kalkuliert mit 2 Tagen)

**Comment by tbaddade** [comment]
Je nach dem was passiert muss dieses Ticket mit beachtet werden https://github.com/yakamara/redaxo_prozer/issues/230
