### ISSUE TITLE
Darstellungsfehler Monat März 

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#240]
Der Monat März wird wegen seines Umlautes falsch dargestellt. (siehe Screenshot anbei) Bitte korrigieren.
![prozer bug](https://cloud.githubusercontent.com/assets/2972659/6575762/260d54f2-c732-11e4-988c-f0312fd13bed.jpg)

**Comment by frag-seb** [comment]
Lösung in line 718 und ab 728 bis 730, wäre somit erledigt.
