### ISSUE TITLE
Projekte - Übersicht nach Projektverwalter sortieren

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#245]

**Comment by frag-seb** [comment]
Soll es ein eigen Filter hierfür geben, wie hast du die die Sortierung vorgestellt?

**Comment by Christian-H** [comment]
Gute Frage. 
Eigentlich dachte ich einfach, man klickt daraufl, dann sortiert sich die Liste nach Projektverwalter alphabetisch aufsteigend. Wenn man nochmal darauf abklickt, dann absteigend. 
(Das wäre auch gut für die Sortierung beim Erstelldatum) 
Was machenwir aber, wenn es mehrere Projektverwalter gibt? Das Ziel soll ja eine einfache Übersicht sein, welcher Projektverwalter welche Projekte hat und wie viele? 
Das ginge dann nur über eine Projektfilter mit aktiven Projektverwalter (bitte nicht alle User im Filter) . Am besten in Klammern dahinter, für wie viele Projekte jemand verwaltet. 
Wie aufwendig ist das undspricht was dagegen? Wenn es zum Beispiel Performance Einbußen gibt, dann nein :-)

**Comment by frag-seb** [comment]
Sortierung Erstelldatum ist kein problem, die Sortierung nach verwalter müsste dann wie du es schon geschrieben hast, über ein Filter gehen.
Da müsste man dann schauen wie wir es genau machen..

**Comment by Christian-H** [comment]
Bitte die Sortierung nach Erstelldatum umsetzen. 

Links im Suchfeld ist es jetzt schon möglich nach "Name", "Label" und "Kunde" zu suchen. Bitte ergänze dort das Feld "Projektverwalter" und entweder ist es ein:
- Ein Freidfeld, wo ich den Namen eingebe, oder
- es ist ein Auswahlfeld, indem nur alle aktiven Projektverwalter angezeigt werden oder
- es ist ein Auswahlfeld(drop-down), wo alle aktiven User ausgewählt werden könnne.
Wobei der leztteVorschlag am wenigsten gewollt ist.
