### ISSUE TITLE
Adressen - Bild Upload optimieren

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#248]
Prüfen ob Format stimmt + Wenn mehrere Bilder hochgeladen werden, visuell abfangen

**Comment by frag-seb** [comment]
Bild Format meinst Du width & height, wenn nicht musst du mir genauer erklären was Du meinst.
Warum kann man mehere Bilder hochladen?

**Comment by Christian-H** [comment]
Mmh, ich überlege, ob man daran noch arbeiten muss? 
Es ist so, dass über Drag and Drop mehrere Bilder hochgeladen werden können und dann das letzte genommen wird. Was sicherlich an der allg. upload Schnittstelle liegt. 
Es werden auch Bilder,ohne das eine Fehlermeldung kommt, hochgeladen und nicht angezeigt, wie bmp oder tiff-dateien. 

Da aber dadurch trotzdem nichts falsch gehen kann, würde ich da jetzt keine weitere Arbeit hinein investieren. 

Denn schlimmstenfalls ist halt kein Bild da oder der Ausschnitt falsch. Egal.
