### ISSUE TITLE
Projektverwaltung: Ordner löschen/verschieben nicht möglich

### ISSUE THREAD

**Issue by UliK** [yakamara/redaxo_prozer#25]
In der Projektverwaltung fehlt die Möglichkeit, vorhandene Ordner zu löschen oder sie innerhalb der Ordnerhirarchie zu verschieben. Man kann nur immer neue Ordner anlegen, das reicht aber nicht...

**Comment by frag-seb** [comment]
Diese Möglichkeit Ordner zu löschen und auch verschieben.
