### ISSUE TITLE
Idee - Newsticker

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#252]
Gerade hatte ich die Idee, dass ganz oben ein agenturweiter oder persönlicher Newsticker laufen könnte. Darin könnte folgender Inhalt sein:
- Geburtstage an de Tag
- Neueste E-Mail der letzten 15 Min. oder auch die letzten drei, mit Absender und Subject 
- Terminerinnerung
- News aus einem Forum, News.... oder ähnlichem 
- News aus RSS-Feed? Wie Google Alert? 
- Adresse die neu angelegt wurde oder update gerade hatte?
- ....

**Comment by dergel** [comment]
Würde ich mir hier hineinnehmen.. Ganz was Neues was wieder Platz oben saugt würde ich nicht machen. deswegen Verweis #206
