### ISSUE TITLE
E-Mail - Default Einstellung Sortierung - ungelesen einzustellen

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#253]
Es wurde der Wunsch geäussert, dass die ungelesen Nachrichten per Default als erstes angezeigt werden. Ist in Gmail möglich siehe Screenshot und deren weitere Sortiermöglichkeiten.
Dies unterstütz meiner Meinung nach gut die Arbeit von Sortierten Personen, die tatsächlich nur bis max. 40 E-Mails in Ihrem Postfach haben, wie vom Konzept her auch gedacht, weshalb ich den Vorschlag gut finde und unterstütze. 
![e-mail-sortierungmoglichkeiten-gmail-20150313](https://cloud.githubusercontent.com/assets/2972659/6636606/09ed260c-c972-11e4-9df8-72770092b2ad.jpg)

**Comment by dergel** [comment]
d.h. erst ungelesene und dann nach Datum sortieren.. Und ungelesene IMMER zuerst ? also auch wenn ich andere Sortierkriterien verwende ? Das E-Mail Kriterium "Priority" ignorieren wir komplett.

**Comment by dergel** [comment]
man kann im Moment ungelesene Mails durch die Suche filtern

**Comment by Christian-H** [comment]
Es ging dabei um die default - Einstellung auf Ungelesene zuerst zu setzen. Da es aber nur eine Person bisher braucht und Sie tatsächlich ggf. mit dem Filter arbeiten kann, schließen wir das Issue.
