### ISSUE TITLE
Termin mit Einladungen in Jobliste

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#263]
Wenn eine Person einen Termin mit Einladung von 1 oder mehr erstellt, es sich dann aber anders überlegt und das Job - Häkchen anklickt, dann verwschwindet zwar die Leiste mit den Einladungen. Wird dieser  Termin/Job aber abgeschickt, ist die Einladung noch vorhanden. Damit erhält der Eingeladene einen Termin in derJobspalte, was einen dann verwirrt. 
D.h.meiner Meinung nach, wenn das Job-Häkchen angeklickt wird, müsste die Einladungn nciht nur visuell verschwinden, sondern auch funktional.

**Comment by frag-seb** [comment]
Der Fehler lang darin das die Teilnehmer nicht richtig gelöscht wurden, also ein reset des Forms gemacht wurde.
