### ISSUE TITLE
E-Mails in Alle E-Mails

### ISSUE THREAD

**Issue by frag-seb** [yakamara/redaxo_prozer#267]
Ist das richtig so? 
Wenn ein Projekt archiviert, fehlt die Zuordnung der E-Mail in der Übersichte "Alle E-Mails".

1) Sollte diese E-Mail dort noch angezeigt werden? 
2) E-Mails sollte noch angezeigt werden mit Projekt und die Möglichkeit es zu ändern gesperrt?

**Comment by dergel** [comment]
das ist so gewollt. Archiviert heisst - weg vom Fenster..

**Comment by frag-seb** [comment]
Bin nicht sicher ob ich es richtig erklärt hab, die E-Mail wird einfach ohne bemerkung oder so in der Übersicht "Alle E-Mails" angezeigt. 

weg vom Fenster, würde heißen man kann sie nicht mehr sehen.
