### ISSUE TITLE
Fehler E-Mail Upload

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#28]
E-Mail wir angelegt - > 3 (oder auch 2 ausprobiert) Dateien angehangen (Bei uns per Drag and drop)- > Gemerkt, dass man noch was an den Dateien verenden möchte - > Aus Liste entfernen gedrückt -> Dateien bearbeitet -> per Drag and Drop wieder 3 Dateien angehangen -> E-Mail versenden drücken - > Outbox nachsehen, 2 Dateien wurden doppelt versendet, also insgesamt 5 Dateien -> Fehler

Das selbe Beispiel mit 2 Dateien - > Am Ende drei Dateien versendet, wovon eine doppelt waren.

**Comment by Christian-H** [comment]
Mmh, ich konnte de Fehler nicht reproduzieren, aber den wieder gesehen, dass ich nach dem upload von drei Dateien gleichzeitig nur die unterste löschen kann, aber nicht die zwei ersten von oben.

**Comment by dergel** [comment]
kannst du das nachvollziehen @frag-seb  und prüfen ?

**Comment by frag-seb** [comment]
Ja, der Fehler besteht wenn man mehrere Dateien gleichzeitig auswählt und dadurch kann es auch sein das Dateien Doppelt versendet werden.

Bin dran!

**Comment by frag-seb** [comment]
Das gehört doch zusammen

 Mailanhang: Der oberste kann nicht gelöscht werden #197

**Comment by frag-seb** [comment]
Der Fehler ist fixed, ich warte mit dem Pull Request noch, bis #269 merged ist.
