### ISSUE TITLE
Termin über 2 Tagen wird farblich falsch dargestellt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_prozer#286]
Ich hatte einen Termin über 2 Tage eingetragen.

Bsp. 3.5. - 4.5.2015 - 13:00 - 14:00 Uhr

Die farbliche Darstellung war dann jeweils eine Stunde am
3.5. 13:00 - 14:00 Uhr und
4.5. 13:00 - 14:00 Uhr anstatt

3.5. 13:00 - 4.5. 14:00 Uhr

**Comment by frag-seb** [comment]
@tbaddade Kannst du mal bitte schauen ob das bei version 3.1 noch so ist? Sollte wenn ich den Bug richtig verstanden hab schon behoben sein.

**Comment by tbaddade** [comment]
> Sollte wenn ich den Bug richtig verstanden hab schon behoben sein.

Stimmt, ist behoben
