### ISSUE TITLE
Link in HTML E-Mail in externen Fenster öffnen

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#287]
Bitte stellt es so ein, dass Hyperlinks in HTML-E-Mails sich in einem neuen Fenster öffnen. Ich klicke schon oft einen link an und die neue Seite öffnet sich im Prozer im HTML Fenster der E-Mail. Dann muss ich den zurück Button betätigen und rechte Maustaste, den Link im neuen Fenster anklicken.
(Und bitte kommt mir nicht mit der Standard Programmierer Antwort "Mir ist die Wahlfreiheit wichtig und es kann doch mit der rechten Maustaste ein neues Fenster geöffnet werden". Aber das sind nur ca. 5% der User ;-) )

**Comment by frag-seb** [comment]
misst :D

**Comment by tbaddade** [comment]
Duplicate #182
