### ISSUE TITLE
Kunden editieren geht nicht mehr

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#289]
Kann einen existierenden Kunden nicht mehr editieren und somit ihm auch kein Logo zuweisen :-)

**Comment by frag-seb** [comment]
komme ich erst Morgen dran..

**Comment by Christian-H** [comment]
.... alles klar, kannst auch erst am we daran arbeiten :-) wie du halt kannst ....

**Comment by frag-seb** [comment]
Bitte erklär mir mal was genau nicht geht, ich kann Kunden edit und bilder hinzufügen?

**Comment by Christian-H** [comment]
Upsi, Pupsi, da dachte ich wohl,dass müsste aufklappen. Sorry. Also es geht.
