### ISSUE TITLE
Tools - Jobs - Einträge direkt editieren zu können

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#295]
An sich ist diese Übersicht wirklich klasse, vor allem, wenn man bedenkt, dass man schnell die Jobs auf Rechtschreibfehler überprüfen möchte oder ich eine doppelte Jobbuchung sehe oder ..., damit daraus später eine anständige Rechnung wird. Doch wenn ich einen sehe, dann ist es mir zu umständlich diesen Termin im Kalender zu suchen. 

Von daher schlage ich vor, dass ein Termin dort direkt bearbeitet werden kann, am besten direkt in der Tabelle und nicht in einem Feld was erst aufgeht. Das wäre das Optimum und Lösungsansatz 1. 
1b Lösung: Projekt, Datum und Uhrzeit sind nicht editierbar. Dafür kann ich direkt "Titel" und "Beschreibung" editieren. 
2b: Es gibt ein Symbol und wenn ich darauf klicke, lande ich direkt im Kalender und kann den ausgewählten Termin direkt im Formularfeld bearbeiten.

**Comment by dergel** [comment]
sehe ich das falsch oder haben wir das nicht schon drin was du meinst ..

Bei unserer aktuellen version kann ich im /screen/tools/jobs/ Bereich einen Job anklicken, der sich dann links öffnen und bearbeiten lässt. Ist zwar vom Ablauf nicht so wie von Dir beschrieben, aber die Möglichkeit ist bereits da. Ich denke auch ok so wie es ist.

**Comment by Christian-H** [comment]
Ja, Jochen hat das gemacht und ich habe das Feature noch nicht:
 Jobs #42 #301
