### ISSUE TITLE
javascript listener pattern 

### ISSUE THREAD

**Issue by frag-seb** [yakamara/redaxo_prozer#300]
Was haltet Ihr davon, das wir ein Javascript Listener schreiben, in dem wir events die ausgeführt werden sollen, eintragen können.
Idee dahinter ist, z.B, pz_loadFormPage soll danach in einer definierten Reihenfolge noch verschiede andere Aktionen ausführen. 
Mit dem Listener können wir einfach, an die Aktion was dran hängen ohne großen Aufwand und hätten dann sauber entkoppelte Funktionen.
Das ganze könnten wir mit js promise dann when .. then aublaufen lassen.

**Comment by dergel** [comment]
finde ich gut .. aber wollen wir erstmal grundsätzlich nachdenken, ob wir nicht neue bibliotheken verwenden und vielleicht das ganze javascript umbauen ? ich würde das nicht hier nicht einzeln angehen wollen

**Comment by frag-seb** [comment]
War eher "Es Nervt mich gerade!" Issues :D 

Ja das ist mir sogar viel lieber, wann meinst du, dass wir damit anfangen sollten? 
Brauchen dann eine Liste der Anforderung und es wird auch sicherlich notwendig werden, Serverseitig Änderungen dann vorzunehmen.

**Comment by frag-seb** [comment]
Gehört hier rein #315
