### ISSUE TITLE
Kalender Denglish

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#304]
Wieso sind die Wochentage in Englisch geschrieben und nicht Deutsch? 
Wieso sind bei Einladungen die Monate in englisch geschrieben und nicht Deutsch? Im Kalender werden Sie in Deutsch angezeigt. 
(siehe Screenshot anbei)
![kalender-denglish-20150608](https://cloud.githubusercontent.com/assets/2972659/8031187/b8800ae2-0dcc-11e5-8de7-0da2d84a341e.jpg)

Ich schlage vor, dass zu ändern.

**Comment by frag-seb** [comment]
Werde ich heute Abend beheben, ich glaub, mir ist dazu schon einmal was aufgefallen. Muss schauen ob es wirklich daran liegt.

setlocale in file ??  wird nur mit de_DE ausgeführt, damit aber auch LC_TIME richtig übersetzt wird muss dahinter eigentlich noch .UTF-8. Kann aber jetzt auch sein das ich das nicht im Prozer gesehen hab. 

Lösung sollte sein:

setlocale(LC_ALL, array('de_DE.UTF-8', 'de_DE'));

Heute Abend wird es behoben sein.. :D

**Comment by gharlan** [comment]
Interessanterweise ist bei uns hier alles deutsch:

![screenshot 2015-06-08 11 43 35](https://cloud.githubusercontent.com/assets/330436/8032071/acae50b4-0dd3-11e5-8aa5-4c351f7742b3.png)

@frag-seb Du hast aber Recht, setlocale wird nur ohne ".UTF-8" gesetzt.

**Comment by frag-seb** [comment]
Ist gut möglich, das es bei dem einen oder anderen geht.. 

![iss304](https://cloud.githubusercontent.com/assets/1322118/8032318/67569196-0dd5-11e5-9652-7c7cf59be1c2.PNG)

Ich hatte das problem schon öfter und kenne nur die Lösung, verstanden warum, hab ich aus mangel von unterschiedlichen test system leider nicht.

**Comment by frag-seb** [comment]
Musst dir mal das verhalten von setlocale mit threads anschauen wirst verrückt :D

**Comment by gharlan** [comment]
> Ich hatte das problem schon öfter und kenne nur die Lösung, verstanden warum, hab ich aus mangel von unterschiedlichen test system leider nicht.

Jupp, wird schon passen. Habe das auch so im Hinterkopf, dass es da auf verschiedenen Systemen Unterschiede im Verhalten gibt.

**Comment by frag-seb** [comment]
LOL, daheim auf dem Mac ist es auch bei mir richtig :D

**Comment by frag-seb** [comment]
Es liegt daran das auf dem Server das Sprachpaket de_DE nicht installiert ist, kann man aber wie gesagt schön umgehen.

Konnte es jetzt schön testen...
