### ISSUE TITLE
Job über 2 Tage

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_prozer#31]
Bspl:
01.03. - 10:00 Uhr bis 02.03. - 11:00 Uhr

Job wird im Kalender angezeigt am
01.03. > 10:00 - 11:00 Uhr

Job wird unter User/Jobs falsch in der Gesamtzeit eingerechnet (1 Stunde)

Eine Zeit wie
01.03. - 10:00 Uhr bis 02.03. - 08:00 Uhr
ist ja nicht möglich, daher Jobs über mehrere Tage eher generell verbieten?

**Comment by frag-seb** [comment]
@dergel Kannst Du mir hierzu etwas sagen?

z.B. verbieten und bei Jobs nur ein Datums-feld?

**Comment by dergel** [comment]
die anzeige und berechnung ist falsch.. das sollte erlaubt sein.
