### ISSUE TITLE
Rote Meldung bei leerem Postfach

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_prozer#313]
Mein Postfach sieht regelmäßig so aus:

![screenshot 2015-06-18 10 41 18](https://cloud.githubusercontent.com/assets/330436/8227341/cb0a6478-15a6-11e5-9c7f-55540fce19e8.png)

Ich finde diese rote Meldung nicht so passend. Es ist ja kein Fehler, sondern gut, dass ich alle Mails abgearbeitet hab.

**Comment by dergel** [comment]
ja.. sollte eher grün sein .. und nur wenn man keine Suche gestartet hat
