### ISSUE TITLE
Weiterleitung nach Termin hinzufügen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_prozer#314]
führt zu Problemen. Wenn man schneller ist und einen neuen Termin anlegen will, dann verschwindet der plötzlich. Wahrscheinlich gibt es irgendwo ein setIntervall welches dann erst aufgeführt wird. Zusätzlich scheint mir, dass das aktuelle Datum nicht mehr gesetzt ist. Das wird normalerweise vom aktuellen Tag genommen.. @frag-seb kannst du nochmal nachschauen ?

**Comment by gharlan** [comment]
Jupp, passiert mir auch regelmäßig. Job angelegt, will direkt den nächsten anlegen, fang schon an zu tippen, und dann lädt es plötzlich nochmal neu und meine Eingaben sind weg.

**Comment by frag-seb** [comment]
Ja, schau es mir an...

**Comment by frag-seb** [comment]
Der Fehler das die Seite sich neu Lädt, wenn man schon auf den Button geklickt hat ist behoben.

Das aktuelle Datum verhält sich wie zuvor, es wird das Datum mit gegeben dadurch wird wird die Uhr auf 12:00 Uhr gestellt.

Warum wurde das explizit so gemacht, wäre es nicht besser das es so ist wie wenn man auf Kalendar Klickt und sich die Zeit auf jetzt bezieht?

**Comment by gharlan** [comment]
Ich wollte gerade für Donnerstag und Freitag Jobs nachtragen (zwei 8-Stunden-Jobs). Bin also auf Donnerstag, neuer Job, ausfüllen, speichern.
Dann bin ich einen Tag weiter, gewohnheitsmäßig auf neuer Job geklickt, angefangen auszufüllen, Bereich lädt neu (Fix ist bei uns ja noch nicht drin), Daten erneut ausgefüllt, gespeichert.
Nun habe ich gesehen, dass der Job für heute statt für Freitag angelegt wurde. Das Datum hat sich wohl geändert bei dem Neuladen des Formulars.

Verstehe ich das richtig, dass es nach dem Fix dann wieder "richtig" funktioniert? Also wenn ich bei einem vergangenen Tag auf "Neuer Job" klicke, dann ist auch das Datum ausgewählt?

PS: Beim Neuladen des Formulars wurde dann auch die Zeit angepasst. Ich musste also die Minuten selbst auf :00 stellen, für den 8-Stunden-Job, 10:00 – 18.00 Uhr. Dementsprechend bin ich auch hier dagegen. ;)

**Comment by tbaddade** [comment]
Zum Datum kurz. Es war immer so, dass das Datum beim "Termin anlegen" aus dem Kalender übernommen wurde. Es ist nicht auf das heutige Datum gesprungen. Wenn ich @gharlan richtig verstand, ist dies bei ihm jedoch so geschehen.

Wegen der zeit, ist es mir recht egal. Ich muss diese immer anpassen. Man sollte nur die Minuten von den Stunden ein wenig besser abheben.

**Comment by frag-seb** [comment]
@tbaddade Das From wird wird jetzt neu geladen, wenn man einen angelegt hat. Dadurch kommt es jetzt dazu das der heutige Tag genommen wird. 

@gharlan Muss ich mit heute Abend ansehen, also wenn du das Kalender Datum geändert hast, wird das Form glaub noch neu Laden. Wird geprüft...

**Comment by tbaddade** [comment]
> Das From wird wird jetzt neu geladen, wenn man einen angelegt hat. Dadurch kommt es jetzt dazu das der heutige Tag genommen wird.

Wenn ich den 23.06. im Kalender geöffnet habe, sollte nicht der 29.06. voreingestellt sein.

**Comment by frag-seb** [comment]
Wenn du auf dem 23.06 bist und dann auch "Neuen Job" Klickst, wird der 23.06 ausgewählt. Ob dann der 23.06 dann auch beim neu Laden wieder ausgewählt wird muss ich prüfen.

**Comment by tbaddade** [comment]
Könnte man den Bugfix zeitnah bei uns einspielen?
