### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by frag-seb** [yakamara/redaxo_prozer#320]
Wo kann ich definieren ob ein Projekt ein Wiki hat oder nicht?

Derzeit ist has_wiki immer 0 und wird doch angezeigt...

**Comment by frag-seb** [comment]
Projektuser gibt es auch keine Möglichkeit....

**Comment by dergel** [comment]
genau.. wiki ist quasi immer freigegeben... sollten wir das als recht mit aufnehmen ? ich bin mir unsicher .. @Christian-H @frag-seb @tbaddade @gharlan

**Comment by gharlan** [comment]
Dieses `has_wiki` in der DB ist glaube ich älter als das eigentliche Wiki.
Und als wir dann das Wiki gebaut haben, haben wir entschieden, das wir dieses `has_wiki` nicht nutzen, haben es dann aber scheinbar auch nicht gelöscht.

Ob es sinnvoll ist oder nicht, da habe ich keine Meinung zu.

**Comment by dergel** [comment]
ich finde das allgemein gut, wenn man es immer hätte.. aber das denke ich auch bei dateien, emails .. ich würde das alles abspecken wollen

**Comment by Christian-H** [comment]
Ja, macht natürlich Sinn das als Recht aufzunehmen. Denn zum einen soll darin ggf. alles verarbeitet werden im wiki und demnach auch Dinge, die vielleicht nicht für alle zu lesen sein sollen. Sprich, wenn ich einem freien Mitarbeiter nur das Recht für Jobs buchen einräume, wieso sollte er dann das wiki sehen können?

**Comment by Christian-H** [comment]
.... wenn es keine diversifizierten rechte gibt, dann ist es keine lösung mehr für agenturen bis 50 personen ....

**Comment by dergel** [comment]
@Christian-H ist es schon ... es ist eine Frage was ich als Projekt definiere und wo ich welche Gruppen sehe... Man kann immer eine neue Gruppe aufmachen... Bezüglich Wiki: Wäre wahrscheinlich nur konsequent dass dann auch hier als Projektrecht aufzunehmen..

**Comment by Christian-H** [comment]
@dergel Ja, kann man, aber dann gibt es wahrscheinlich sehr viele Projekte :-) Nachdem wir ausgemistet haben, sind es zur Zeit "nur" aktive 115 Projekte :-) und das bei unter 20 MA. Und selbst das finden wir fast zu viel. Gerade auch bei Kunden mit sehr sensiblen Themen, ist die Rechteverteilung sehr hilfreich. 
Wenn überhaupt, wäre es ein Überlegung wert, ob "E-Mail", "Dateien" und "Wiki" ein Recht sein könnte, denn wer auf die Inhalte zugreifen darf, bekommt in der Regel auch diese Rechte dann komplett. Nur ob ich das hier durch bekomme und ob Programmier-technisch Sinn macht, bezweifle ich im Moment.

**Comment by frag-seb** [comment]
Ich finde im Projekt kann es immer aktvie sein, nur für User sollte man die Wahl haben. 

Wenn man es ganz entfernt sollte man dann auch die DB und code aufräumen und die "has_wiki" entfernen.

**Comment by dergel** [comment]
Projektrechte können wir ruhig lassen, das kann ich verstehen, dass man diese Unterscheidung will. Das Wiki müssen wir noch extra aufnehmen. Das ist dann konsequent und richtig.

**Comment by dergel** [comment]
@frag-seb willst du das machen ? 

* Projektrechte hinzufügen - im Projekt . /screen/project/user/?project_id=x
* Ansicht auf der eigenen Rechtseite . /screen/tools/
* Rechtemethoden anlegen (kann sein, dass es die schon gibt)
* Projekt anlegen /screen/projects/
* Projekt bearbeiten /screen/project/view/?project_id=x

das müssten die Stellen sein.

**Comment by dergel** [comment]
hast du schon was gemacht jochen ? .. wenn nein, dann würde ich das angehen ..

**Comment by dergel** [comment]
ich mach das mit dem wiki

**Comment by frag-seb** [comment]
Ich hab es schon gemacht

**Comment by frag-seb** [comment]
Hab es noch getestet und wollte es heute Abend pushen

**Comment by dergel** [comment]
ah ok .. dann nehme ich alles zurück :)

**Comment by dergel** [comment]
hast du eine chance das jetzt schon zu pushen.. brauche die funktionen um weiterzumachen

**Comment by frag-seb** [comment]
Ne, leider erst so ca. 16:30 Uhr, dann dürfe ich daheim sein..

**Comment by dergel** [comment]
ok ..
