### ISSUE TITLE
Kunde - Logo - Clipboard nicht nutzbar

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#325]
Unter Kunden, kann ich das Logo nicht aus dem Clipboard nehmen und kann es "nur" hochladen. Ist eine Kleinigkeit und muss nicht schnell bearbeitet werden. Nehme es mal auf, da es an sich sonst nicht konsequent umgesetzt ist.

**Comment by frag-seb** [comment]
Ich werde das auch noch auf der  (/screen/addresses/) Page ändern...

**Comment by frag-seb** [comment]
@dergel  @gharlan 

[Code](https://github.com/frag-seb/redaxo_prozer/blob/Issues_320/lib/pz.php#L603-L613)
```php
            ob_start();
            switch ($mimetype) {
                case('image/jpeg'):
                case('image/jpg'):
                    imagePNG($src, null);
                    $mimetype = 'image/jpg';
                    break;
                default:
                    imagePNG($src, null);
                    $mimetype = 'image/png';
            }
```
Kurze frage an euch, auf meinem Mac funktioniert das so nicht und warum muss es unbeding imagepng sein?
```php
            ob_start();
            switch ($mimetype) {
                case('image/jpeg'):
                case('image/jpg'):
                    imagejpeg($src, null);
                    $mimetype = 'image/jpg';
                    break;
                default:
                    imagepng($src, null);
                    $mimetype = 'image/png';
            }
```
Wäre es so nicht besser?
