### ISSUE TITLE
Reiter "Tools"  - Wieso heisst der so? 

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#326]
Den Namen finde ich dafür unglücklich: 
- Wieso ist er der einzige auf Englisch, wenn die anderen auf Deutsch sind? 
- Ist das nicht "Einstellungen" und dann könnte man auch das Grafik - Icon auf Zahnrad stellen. Das Icon finde ich sowieso nicht eindeutig und gelungen. 
Was sind Eure Vorschläge?

**Comment by tbaddade** [comment]
**Einstellungen** ist m.E. auch nicht richtig.
Mein Vorschlag: **Mein Profil und mehr**

**Comment by frag-seb** [comment]
@tbaddade Warum nicht nur Mein Profil? 

Mein Profil fände ich gut

**Comment by Christian-H** [comment]
Gute Diskussion und 2 Vorschläge von mir nach Diskussion mit Franzi:
- Nur "Profil", reicht doch. 
- Icon bleibt so, aber wir ändern das Adressen - Icon, indem wir ein "@" mit hinein nehmen, anstatt den Kopf. Dann gibt es eine größere Unterscheidung auch zu Kalender. Neues Ticket dafür anlegen?

**Comment by tbaddade** [comment]
> Warum nicht nur Mein Profil?

Jobs und E-Mail Setup sehe ich eher nicht als mein Profil an. Daher ein Zusatz wie hier auf Github (oben rechts hover auf das Usericon ) :)

**Comment by frag-seb** [comment]
Dann würde ich aber auch eher Konto wie Profil sagen...

**Comment by Christian-H** [comment]
Gutes Argument Thomas, dann bin ich auch für "Mein Profil und mehr" oder "Einstellungen. Sorry, "Konto" finde ich nicht gut, da zu inhaltslos.

**Comment by frag-seb** [comment]
@dergel kannst Du noch was dazu schreiben :D

**Comment by dergel** [comment]
"Mein Profil und mehr" finde ich gut :)

**Comment by dergel** [comment]
willst du das anpassen jochen ?

**Comment by frag-seb** [comment]
Hab ich doch schon mir assigned

**Comment by frag-seb** [comment]
:D

**Comment by frag-seb** [comment]
@dergel 
> Icon bleibt so, aber wir ändern das Adressen - Icon, indem wir ein "@" mit hinein nehmen, anstatt den Kopf. Dann gibt es eine größere Unterscheidung auch zu Kalender. Neues Ticket dafür anlegen?

Soll ich das Icon auch ändern?

**Comment by dergel** [comment]
ach so .. habe ich übersehen.. ob da ein @ oder sonstwas rein soll schauen wir mal .. das kommt ein anderes mal..  erstmal nur text
