### ISSUE TITLE
Wochenansicht - Termin verschieben ist fehlerhaft

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_prozer#329]
In der Wochenansicht wird beim verschieben eines Termines die Woche davor genommen, so dass der Termin aus der aktuellen Ansicht verschwindet

@frag-seb Willst Du Dir das ansehen ? das wäre super.

**Comment by frag-seb** [comment]
Ja, klar schau es mir an glaube weiß auch schon warum. Weil wir ja nur noch die wochenansicht haben dürfte die Berechnung sich geändert haben dafür.

**Comment by frag-seb** [comment]
Oh, das geschieht nur mit alten Einträgen, kannst du bitte schauen ob das bei dir auch so ist.

**Comment by dergel** [comment]
stimmt .. ist bei mir auch so .. ab termine von gestern..

**Comment by frag-seb** [comment]
Also, bei mir war es am Anfang und jetzt ist der Fehler wie du in beschreibst weg. ABER wenn ich am ersten Tag der Woche einen Termin verschieben will, wird er in die Woche davor verschoben, hab den Bug aber gefunden... Endlich ...

Ich würde gerne den Kalender bald neu machen, wäre aber etwas mehr aufwand und ich würde dafür gerne einen neun Branch aufmachen. Wenn @Christian-H und Du damit einverstanden sind, würde gerne aber dann mit dir kurt telefonieren.

**Comment by frag-seb** [comment]
Es gibt ein draggable Event was auf $("#calendar_events_week_list .dragable2") wartet... :D 

Braucht man das noch???

**Comment by frag-seb** [comment]
@dergel Kannst Du das bitte nochmal auf einem test System Prüfen?

Ich kann den ursprünglichen Fehler nur am Anfang erzeugen, den zweiten Fehler ist hier mit behoben.

**Comment by Christian-H** [comment]
@frag-seb Wieso würdest du gerne den Kalender neu machen? Was für Vorteile hätte das für uns? Und was heißt "mehr Aufwand" in Stunden? Ich würde halt gern erst weitere Issues bearbeiten oder ein Dashboard haben, bevor wir an "Feinheiten" arbeiten, was grundsätzlich gut funktioniert.
