### ISSUE TITLE
Navi Bild - Adressen Navi Grafik austauschen

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#332]
für eine größere Unterscheidung zum Reiter "Mein Profil und mehr". 

Ein Vorschlag ist, dass ein "@" Zeichen drin ist.

**Comment by tbaddade** [comment]
> für eine größere Unterscheidung zum Reiter "Mein Profil und mehr".

Ich bin für Zahnräder bei "Mein Profil und mehr" :)

**Comment by Christian-H** [comment]
Finde ich auch gut. Hauptsache es wird eines von beiden Symbolen geändert :-)

**Comment by dergel** [comment]
symbole sind geändert
