### ISSUE TITLE
Mail Empfang Problem HTML Mail

### ISSUE THREAD

**Issue by chip75** [yakamara/redaxo_prozer#333]
![screenshot 2015-07-16 17 36 43](https://cloud.githubusercontent.com/assets/1301303/8727689/575f30c0-2be1-11e5-917e-9006554491cc.png)

Mail als .eml

https://www.dropbox.com/s/946ct9rdxc22yuv/593022.eml?dl=0

**Comment by dergel** [comment]
schon erledigt .. war nur temporär bei uns
