### ISSUE TITLE
Anderer Kalender - Datei anhängen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_prozer#335]
christian: In dem Zusammenhang wurde auch festgestellt, dass seit dem Update, eine Person in einem anderen Kalender nichts mehr an ein Termin dran hängen kann. (Bsp: Also ich bin im Agentur Kalender und möchte dort dem Agentur Termin eine Datei anhängen, geht nicht.) Wird für Reiseunterlagen für den Chef gebraucht :-)

**Comment by dergel** [comment]
@Christian-H kannst du mir das nochmal genauer beschreiben ? wer hat einen termin angelegt, in welchem projekt und hat der user die rechte auf das projekt oder nur einladungen etc .. blicks gerade nicht

**Comment by Christian-H** [comment]
Ich - CHA - möchte im anderen Account - in dem Fall Agentur oder GF/MBE, der mir dir Kalender Rechte auch schreiben gegeben hat, eine Datei an einen Termin dran hängen. Das geht nicht. Verstanden?

**Comment by dergel** [comment]
alles klar.. das geht bereits ..
