### ISSUE TITLE
Anmerkung - Projektteilnehmer

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#34]
Liste Projektteilnehmer scrollbar machen, da im Durchschnitt 10-20 Personen auf ein Projekt zugelassen sind.

**Comment by frag-seb** [comment]
![projektteilnehmer](https://cloud.githubusercontent.com/assets/1322118/7867583/3fa6d662-0577-11e5-829e-c8bc1b696476.jpg)


Meinst Du wirklich diese Seite??

**Comment by Christian-H** [comment]
Ja und ich meine, dass das scrollen automatisch beginnt, wie es bei E-mails sein sollte. 
![e-mail-scrollen](https://cloud.githubusercontent.com/assets/2972659/7878233/00657a8a-05e5-11e5-8863-942cd2aa5f06.jpg)

Die Prio davon ist aber echt niedrig :-)
