### ISSUE TITLE
Wenn ich einen Termin als Job kopiere, soll auch der Status sich von wartend auf Bestätigen ändern

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#340]
Bei uns ist ein Anwendungsfall für Termine, dass wenn sich 2 oder mehr Personen treffen, nach dem Termin einer für alle einen Termin einstellt, damit für den Etatleiter bzw. dem Kunden später alle die gleiche Uhrzeit in der Jobliste haben mit dem selben Titel. 
Dadurch, dass der Termin als Status "wartend" hat, sehe ich den neuen Termin und klicke dann "Job kopieren". Dann muss ich aber noch den Termin bestätigen, damit ich ihn ja nicht mehr jedes mal sehe. 
Also ist es doch logisch, dass wenn ich einen Job kopiere, dass der Termin sich bei mir auf "bestätigt" wechselt. Denn ich trage ja nur einen Job ein, an dem ich auch teilgenommen habe. 
Ich erkenne auch keinen Widerspruch, wenn wir das so machen.

**Comment by frag-seb** [comment]
Richtig wäre das du nur Terminen die du bestätigt hast, kopieren kannst. 

Klar ist es so einfacher, aber nicht jeder nutzt es so.  Ist wieder was wo automatisch geschehen soll, es aber eine klare Handlung erfordert.

Das ist mal meine Meinung...

**Comment by Christian-H** [comment]
Von der Logik und im Sinne eine Prozesses ist es richtig, dass du erst einen Job kopieren dürftest, wenn es bestätigt ist. Doch Menschen und das Leben sind nicht immer logisch. 
Software wird auch oft anders benutzt als mal vom Programmierer gedacht. (Ist nicht Twitter sogar so ein Beispiel :-) ) 
Von daher würde ich es doch gerne einbauen, wenn technisch nichts dagegen spricht, wie das ist nicht in CalDAV vorgesehen und wir müssten das bei jedem CalDAV Update neu einbauen.

**Comment by frag-seb** [comment]
Ich versteh nicht was das mit Programmierer zu tun hat.... Einfach dinge zu tun die ich als User, gar nicht mehr nachvollziehen kann finde ich nicht ok.

Wenn man das so macht ist es ein ganz spezielles feature für euch und du nimmst anderen die frei Wahl.
Wenn du dein Auto absperrst, gehst du ja auch nicht davon aus du hast es somit verschenkt.

Eine andere Möglichkeit wäre das ein confirm popup, wo man gefragt wird, ob man an dem Termin teilgenommen hat.. oder sowas ..

**Comment by Christian-H** [comment]
wenn man einen job kopiert, dann hat man auch daran teilgenommen. es kann doch sein, dass ein termin kurzfristig angesetzt ist, ich das vorher gar nicht mehr bestätigen kann. ich im nachhinein dann aber trotzdem zweimal klicken muss. 
also:
1. wenn ich einen job kopiere und sich der status dann in "bestätigt" wechselt, kann der user das nachvollziehen. 
2. gibt es eine situation, wo dieses automatismus falsch ist? 
 
confirm pop up ist keine möglichkeit. mich nervt diese unnötiger klick, der logisch ist und gemacht werden muss, den ich aber automatisieren kann, da er, meiner meinung nach, immer sinn macht.
das ist auch kein besonderes feature in dem sinn, sondern macht für jeden sinn. außer du findest eine situation, wo es keinen sinn macht bzw. schlichtweg falsch wäre? ich habe sie bisher nicht gefunden.

**Comment by frag-seb** [comment]
Ich glaub ich versteh es jetzt, besser :D, denke in dem Fall wäre die Bestätigung tatsächlich angebraucht.

**Comment by frag-seb** [comment]
könnte ich also machen, wenn das für alle ok ist.
