### ISSUE TITLE
Projektliste ist in der Suche falsch, wenn man in seinem Profil einen Job editiert

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_prozer#348]
1/ Mein Profil > Jobs
2/ In der Suchmaske ein Projekt auswählen
3/ rechts in der Liste einen Job zum editieren auswählen
4/ In der Suchmaske ist die Projektliste verkehrt (gilt auch, wenn der Job gespeichert wurde)

**Comment by frag-seb** [comment]
@tbaddade Ok, der Fehler wird von Chosen.jquery.js erzeugt. wenn ein teil der Seite neu geladen wird, werden alle Select Felder von chosen neu erzeugt und die erste Select ist das kaputt. 

Ich hab jetzt zum test die neue Version des Plugins eingebaut und es funktioniert, wenn alle damit einverstanden sind würde ich das Plugin Updaten. Ich muss noch den Style anpassen und noch ein bug in dem Plugin beheben. (Der Bug ist nur ein paar Minuten Arbeit, das Plugin verträgt sich nicht so gut mit unserem responsive handling)

@dergel Ist das ok?
