### ISSUE TITLE
Termin verschwindet nach Bestätigung

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#349]
Also nachdem ich Termine bestätigt habe, würde ich es gut finden, wenn die gleich dynamisch damit auch verschwinden würden. 
Zum Beispiel trage ich auch gerne Jobs ein, wenn ich auf der Kalenderseite bin.  Was mache ich aber erst, ich lade die Seite neu, damit das Job-Fenster nicht so weit unten ist. 
Ist das elegant möglich?

**Comment by frag-seb** [comment]
Hi Christian, ja das klappt :D ..
Ich wurde noch nie von mir zu einem Termineingeladen, daher ist mir das noch gar nicht aufgefallen.

Commit kommt ...
