### ISSUE TITLE
Admin - Jobs - bei der Anzeige fehlt der Username

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#361]
Heute habe ich einen seltsamen Eintrag gesehen und dann festgestellt, dass ich gar nicht sehen konnte, wer das gebucht hatte. Dafür hätte ich jetzt ins Projekt gehen müssen und den Eintrag suchen. Geht auch, aber ich fragte mich, ob es nicht sinnvoll und möglich ist, den Benutzernamen in die Tabelle aufzunehmen?

**Comment by frag-seb** [comment]
wurde geändert #378
