### ISSUE TITLE
KW wird doppelt im Kalender angezeigt

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_prozer#363]
Die KW wird neuerdings im Kalender doppelt angezeigt. Interessanterweise unterscheiden sich beide Angaben aber auch noch (KW 36 vs. KW 37), also ist eine wohl falsch.

![screenshot 2015-09-07 09 46 31](https://cloud.githubusercontent.com/assets/330436/9711631/57e18b8c-5545-11e5-89fc-529b4ffde88d.png)

**Comment by frag-seb** [comment]
Werde es heute Abend noch ändern.
