### ISSUE TITLE
Kalender - Termine über mehrere Tage

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#370]
Wieso wird ein Termin, den ich vom 2.10 - 5.10 von 12-14 Uhr eintrage im Prozer Kalender richtig an jedem einzelnen Tag angezeigt, aber bei Jobs werden 50h (Wieso auch 50 und nicht 4 mal 24 h?) gezählt und nicht 8h? 

Ist das ein Fehler oder hängt das mit nicht möglichen Serienterminen zusammen oder ...? 
Wenn es ein Fehler ist, bitte korrigieren. Das würde das buchen von Krankheit und Urlaub enorm bei uns vereinfachen.

**Comment by frag-seb** [comment]
Ich versteh nicht ganz was du gemacht hast und wie es aussieht. 

Also wenn du vom 2.10.2015 12:00Uhr bis zum 5.10.2015 14:00Uhr einen Termin eingetragen hast, dann sind das ca 74 Stunden sein. (hoffe ich hab jetzt richtig überschlagen :D )

Was meinst Du mit 8h und Serienterminen?

**Comment by tbaddade** [comment]
@Christian-H Die Anzeige im Kalender ist verkehrt. Der Termin müsste vom 2.10 - 12:00 Uhr bis zum 5.10. - 14:00 Uhr angezeigt werden. Und nicht wie du es wahrscheinlich erwartest, an jedem Tag jeweils von 12:00 bis 14:00 Uhr.

**Comment by Christian-H** [comment]
@tbaddade Danke für die Info. Erwartet habe ich gar nichts, sondern mich gewundert. Die Leute glauben ja das was Sie sehen :-) 
![kalenderbuchung-mehrere-tage](https://cloud.githubusercontent.com/assets/2972659/10241549/3daa7194-68ea-11e5-85d8-31490b631b92.jpg)
Also wäre es gut, dass zu korrigieren :-)
@frag-seb Sorry, der Trmin ging bis 4.10 und deshalb 50 Std. Uups. 
Mit 8 Stunden und Serienterminen meine ich, dass wir jeden Tag 8 Std. buchen sollen. Wenn ich Urlaub habe, buche ich von 9-17 Uhr jeden Urlaubstag auf meinen Mitarbeiter-Projekt. Mit einem Serientermin könnte ich den ganzen Urlaubszeitraum einer Arbeitswoche mit einer Buchung erledigen.

**Comment by frag-seb** [comment]
Welche Version habt Ihr derzeit Installiert? Die Anzeige habe ich gefixt, die wird jetzt über diesen Zeitraum angezeigt. Das ist auch richtig so, was jetzt fehlt die die Möglichkeit für Serientermine, ausser ich hab das noch nicht gefunden und es gibt es schon.

**Comment by Christian-H** [comment]
Haben die Version 3.0 . Serientermine gehen wohl bisher nur übers Protokoll, also übers iphone oder ... In Prozer selbst ist es noch nicht möglich Serientermine einzugeben.

**Comment by frag-seb** [comment]
Ok, schau ich mir mal an.. mit etwas Glück kann ich es richtig darstellen.

**Comment by frag-seb** [comment]
@Christian-H Ist das Ticket noch aktuell??

**Comment by Christian-H** [comment]
Jein.  Also jetzt ist die Anzeige richtig, dass es einen grauen Balken für den gesamten Zeitraum von 50 Std. gibt. .
D.h. die Anzeige vom grauen Balken ist  identisch mit der Stundenbuchung von 50 Std. . 
Und es gibt noch immer keine Möglichkeit Serientermine einzugeben. Also eigentlich kann das Ticket geschlossen werden, wenn ein neues Ticket für Serientermine (ich habe kein existierendes Issue gefunden) erstellt wurde.

**Comment by frag-seb** [comment]
Also ja :D könntest du dann ein neues Issues aufmachen mit den Anforderungen, für einen Serientermine (oder schauen ob es eins gibt).

Ich close das Ticket, wenn es ok für dich ist.
