### ISSUE TITLE
Probleme mit Ganztagesterminen

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_prozer#379]
Habe gerade nicht die Zeit, es genauer zu analysieren (hole ich noch nach), aber irgendwas stimmt nicht mit den Ganztagesterminen.

Bei uns werden einige Ganztagestermine, die über mehrere Tage gehen als ein Tag zu lang angezeigt.
Auch über Caldav kommen die so an.
Im System kann ich die aus irgendeinem Grund nicht bearbeiten, obwohl es meine sind.
Über Caldav kann ich sie bearbeiten, aber sie bekommen immer einen Tag noch hinzu nach dem Speichern.

**Comment by frag-seb** [comment]
@gharlan Soll ich mir das mal anschauen?

**Comment by gharlan** [comment]
Sehr gerne

**Comment by gharlan** [comment]
Bist du schon dazu gekommen? Schon irgendwas rausgefunden?
Ansonsten werde ich es mir anschauen.

**Comment by frag-seb** [comment]
Nein, bin leider nicht dazu gekommen, hab das Dashboard geschrieben.

https://github.com/frag-seb/redaxo_prozer/tree/feature/issues-206?files=1

Widgets Fehlen noch, Styling und muss noch ein paar sachen gerade ziehen.

Bist du schon dazu gekommen? Schon irgendwas rausgefunden?
Ansonsten werde ich es mir anschauen.

—
Reply to this email directly or view it on GitHub
<https://github.com/yakamara/redaxo_prozer/issues/379#issuecomment-155053533>
.

**Comment by frag-seb** [comment]
Kannst du mal skype an machen?

**Comment by gharlan** [comment]
War ein Problem mit Sabredav.
