### ISSUE TITLE
Eintragung eines Adresseintragen über CardDAV

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_prozer#385]
Es wird immer der User mit der ID=1 als Verwantwortlicher eingetragen - soll aber der User sein, der den Eintrag erstellt hat. (initial) .

**Comment by gharlan** [comment]
created_user_id wird gesetzt, responsible_user_id nicht (gab es glaube ich noch nicht immer).
Beides soll also beim Erstellen gesetzt werden, oder?

Welche Adressen gehören in diese "Meine"-Kategorie? Die ich erstellt habe, oder wo ich zuständig bin, oder beide?
Zurzeit sind es die selbst erstellten (create_user_id).
