### ISSUE TITLE
Adressen - Sortierung nach ID`s 

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#6]
funktioniert nicht, sondern wird dann auch alphabetisch sortiert

**Comment by frag-seb** [comment]
Stimmt und die Sortierung muss anderst rum sein.

 "Älteste ID zuerst" bedeutet doch 1, 2, 3
"Neuste ID zuerst" bedeutet dann 3, 2, 1

Werde es auf jeden Fall so ändern.
