### ISSUE TITLE
Bug: Admin im Projekt

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#62]
Es ist gestern der Fehler aufgetaucht, dass ich als Prozer Admin bei einem Teilnehmer im Projekt die Rechte für E-Mail, Dateien, .. als grünes Häkchen direkt entfernen oder hinzufügen konnte. Der Admin (1 von 2) des Projektes (der kein Prozer Admin ist) konnte dem Projektteilnehmer keine Rechte entziehen. Also nicht die grünen Häkchen entfernen oder hinzufügen kann.

**Comment by frag-seb** [comment]
Dieser Fehler wird sich geändert oder auch gleich erledigt haben, mit deisem Fix #134.

Es ist jetzt so, das ein Project Admin, durch das admin recht alles machen kann, die Rechte werden aber nicht in der DB geändert sondern nur durch den zusatz Admin. Wir könnten/sollen die Rechte aber noch in der DB setzen das ist konsistenter und könnte vielleicht noch ein paar bugs beheben.

Ein System Admin kann immer alles ändern...
