### ISSUE TITLE
Upload bricht ab

### ISSUE THREAD

**Issue by UliK** [yakamara/redaxo_prozer#71]
Öffnet man ein Attachment (aus Mail oder Projektordner) über den Browser, wird dieses "schreibgeschützt" angezeigt. Nach speichern des Dokumentes auf dem Desktop (oder in anderem Ordner), dann bearbeiten und erneutem speichern, kann das Dokument nicht direkt wieder in eine neue Mail hochgeladen werden. Der Upload bricht ab.
*Update*: Das Problem tritt auch auf, wenn man die Datei nicht vorher als Attachment geöffnet hat. Selbst bei Dateien, die man über den Datei-Explorer geöffnet, bearbeitet und dann gespeichert hat, bricht der Upload häufiger ab (mal bei 2%, mal bei 27%, mal bei 50%). Könnte vielleicht mit Einstellungen in Office 2013 oder Windows 8 zu tun haben??? (Browser ist aktueller Firefox)

**Comment by dergel** [comment]
Problem ist nicht (mehr) bekannt.
