### ISSUE TITLE
Loginseite - Lorem ipsum dolor Text ändern oder entfernen oder ...

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#81]
Unter "Software-Updates, Weiternetwicklung und Unterstützung" bitte den Lorem .... Text ändern oder entfernen oder Lobhuddelei auf mich reinschreiben. 

P.S.: Witz des Tages Box könnte dort auch sein, die sich automatisch aktualisiert.

**Comment by frag-seb** [comment]
Hat jemand einen Text den ich dafür verwenden kann?

**Comment by Christian-H** [comment]
Hier unser Vorschlag:
"Als Open Source Software entwickeln die Anwender Prozer ständig weiter, sodass die Funktionen Up-To-Date bleiben. Es gibt regelmäßige Updates, die teils auch agenturindividuelle Wünsche beinhalten. Jede Weiterentwicklung wird geprüft und steht dann allen Anwendern zur Verfügung. So gestaltet die Anwendergemeinde von Prozer gemeinsam eine Agentursoftware, die einfach anzuwenden ist."

**Comment by frag-seb** [comment]
@dergel Ist der Text so in Ordnung, soll ich den Text verwenden?

**Comment by dergel** [comment]
absolut in ordnung.. Eigentlich soll da ein eigener Firmentext rein, inkl. eigenem Logo welchen man austauschen kann.

**Comment by dergel** [comment]
d.h. dieses issue behandelt nur die Änderung vom Text .. ein neuer wird die Änderbarkeit betrachten

**Comment by Christian-H** [comment]
und legst du das issue für die Änderbarkeit im Admin Bereich an?

**Comment by dergel** [comment]
das gibt es schon https://github.com/yakamara/redaxo_prozer/issues/241

**Comment by Christian-H** [comment]
Ah, okay, dann passt das doch so. Der Text als allgemeiner, wenn jemand Prozer sich installiert. Und mit #241 sich dann zukünftig individuell anpassen kann.
