### ISSUE TITLE
2-Wochenansicht mit Termin/Job eingabe unbrauchbar

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#82]
Wenn der Button neuer Termin/Job gedrück wird, geht links die Eingabemaske dafür auf und verschiebt die Wochenansicht ins Unbrauchbare. 

Entweder dort die Buttons wegnehmen oder eine Wochenansicht daraus machen oder ...

**Comment by dergel** [comment]
haben wir rückgängig gemacht .. es gibt nur noch eine wochenansicht
