### ISSUE TITLE
Anderer E-Mail Account - Neue E-Mail - Anhang hochladen - Kontrollöffenen fkt. nicht mehr

### ISSUE THREAD

**Issue by Christian-H** [yakamara/redaxo_prozer#86]
Wenn ich in einem anderen E-Mail Account eine E-Mail versenden will mit Anhang, dann lade ich die Datei hoch. Zur Kontrolle möchte ich Sie öffnen, was aber nicht geht und ich denke, dass anhängen hätte nicht geklappt. Wenn ich die E-Mail versende, dann kommt Sie aber ganz normal an. 
Ist halt Mist, wenn man denkt, dass es nicht fkt.

**Comment by dergel** [comment]
immernoch so ? bug, dann labeln

**Comment by Christian-H** [comment]
Weiß nicht, ob das ein Bug ist, da dann das andere Clipboard betroffen wär. Ein Bug ist es auf jeden Fall, dass ich in einem anderen E-Mail Konto nicht die Anhänge weiterleiten kann.

**Comment by frag-seb** [comment]
@Christian-H Ich kann diesen Bug nicht nachstellen. Kannst du schauen ob es bei dir noch so ist und wenn ja was du da genau machst.

**Comment by Christian-H** [comment]
Ist jetzt okay und schließe ich :-)
