### ISSUE TITLE
Für Skin eigene JS-Datei im Header

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_prozer#94]
Es würde dem eigenen Theme noch mehr Möglichkeiten geben, wenn man ein oder mehrere eigene JS-Datei im Header laden kann.
Im Idealfall kann man sich mit eigenen Aufrufen dahinter klemmen oder auch vorhandene ersetzen.

**Comment by dergel** [comment]
ist bereits seit einiger Zeit drin ..
