### ISSUE TITLE
Fehlende Übersetzung bei Emailversand-Fehlermeldung

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_prozer#96]
Ich weiß dummerweise nicht mehr den Platzhalter, aber die die Meldung, wenn ein Mailversand fehlschlägt und die Mail dann als Entwurf gespeichert wird, ist noch nicht übersetzt.

**Comment by frag-seb** [comment]
Die Übersetzung in in der Aktuellen Version drin.
